name: Build Containerfile

jobs:
  build_with_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build with Docker
      run: |
        docker build -t my-container:docker -f Containerfile .

  build_with_podman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman

    - name: Build with Podman
      run: |
        podman build -t my-container:podman -f Containerfile .