name: Build Containerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_with_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with Docker
      run: docker build -t podmanignore:docker -f Containerfile .

  build_with_podman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with Podman
      run: podman build -t podmanignore:podman -f Containerfile .