name: Build Containerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_with_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Show Docker version
      run: docker --version

    - name: Build with Docker
      run: docker build -t podmanignore:docker -f Containerfile .

  build_with_docker_legacy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Show Docker version
      run: docker --version

    - name: Build with Docker
      run: docker build -t podmanignore:docker -f Containerfile .
      env:
        DOCKER_BUILDKIT: 0

  build_with_podman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Show Podman version
      run: podman --version

    - name: Build with Podman
      run: podman build -t podmanignore:podman -f Containerfile .

  build_with_podman_explicit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Show Podman version
      run: podman --version

    - name: Build with Podman
      run: podman build -t podmanignore:podman -f Containerfile --ignorefile .dockerignore-explicit .